# IntelliJ Platform Artifacts Repositories
# -> https://plugins.jetbrains.com/docs/intellij/intellij-artifacts.html
pluginGroup=com.github.sh41.idea-run-wdio
pluginName=WebdriverIO
pluginVersion=2025.2
# forked from https://github.com/wenqingzhang/idea-run-wdio
pluginRepositoryUrl=https://github.com/sh41/idea-run-wdio
# IntelliJ Platform Properties
# Read more: https://plugins.jetbrains.com/docs/intellij/build-number-ranges.html
platformType=IU
platformVersion=252.4326
pluginSinceBuild=252
pluginUntilBuild=252.*
# Comma-separated list of plugins to build against, if any
bundledPlatformPlugins=JavaScript, NodeJS, com.intellij.modules.ultimate, JavaScriptDebugger
# Plugin Verifier IDE versions
# Read more: https://plugins.jetbrains.com/docs/intellij/plugin-verifier.html
pluginVerifierIdeVersions=2025.2

# Opt-out flag for bundling Kotlin standard library.
# See https://kotlinlang.org/docs/reference/using-gradle.html#dependency-on-the-standard-library for details.
kotlin.stdlib.default.dependency=false

kotlin.code.style=official
